feat: cw dex bindings
neutron-org/neutron-sdk pull request #120
Opened 2023-11-16 12:08 UTC by swelf19

2024-02-16 12:47 UTC, NeverHappened requested changes

2024-02-16 12:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/msg.rs
> +    Deposit {
I think a good idea to add comments to each enum since it's public package

2024-02-16 12:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/query.rs
> +    lower_tick1: Option<PoolReserves>,
isn't it upper_tick1?
https://github.com/neutron-org/neutron/blob/77b35712d6fbd391f289828df422a886775b7088/proto/neutron/dex/pool.proto#L15

2024-02-16 12:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/types.rs
> +    GoodTilCancelled,
comments would be great here

2024-02-16 12:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/types.rs
> +    pub key: LimitOrderTrancheKey,
is it intended to be `pub` only on the `key` field?

2024-02-16 12:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/query.rs
> +    fee_tiers: Vec<u64>,
i think all fields below are private? should we make them public?

2024-02-16 12:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/types.rs
> +    trade_pair_id: TradePairID,
pub?

2024-02-20 12:28 UTC, pr0n00gler reviewed
LGTM for me, but please resolve the comments above

2024-02-22 18:30 UTC, pr0n00gler approved these changes

2024-02-23 10:32 UTC, NeverHappened submitted a review, later dismissed

2024-03-19 13:55 UTC, pr0n00gler approved these changes

2024-03-20 08:51 UTC, merged