NTRN-201 fix potential overflow during delegations reconstruct
neutron-org/neutron-sdk pull request #132
Opened 2024-02-22 14:15 UTC by quasisamurai

Task: NTRN-201 https://hadronlabs.atlassian.net/browse/NTRN-201

I also checked other fns, didn't find any potential overflows.

2024-02-22 19:12 UTC, pr0n00gler requested changes

2024-02-22 19:12 UTC, pr0n00gler commented on packages/neutron-sdk/src/interchain_queries/v045/testing.rs
> +fn overflov_test() {
I don't think we need this one, it's just some printlns

2024-02-23 12:58 UTC, pr0n00gler commented
Please fix clippy issue

2024-02-23 14:58 UTC, pr0n00gler approved these changes

2024-02-23 15:09 UTC, NeverHappened requested changes

2024-02-28 14:12 UTC, NeverHappened approved these changes

2024-02-29 11:05 UTC, swelf19 approved these changes

2024-03-04 20:23 UTC, pr0n00gler approved these changes

2024-03-05 10:19 UTC, merged