NTRN-260 slinky bindings (market map & oracle)
neutron-org/neutron-sdk pull request #141
Opened 2024-05-06 21:45 UTC by quasisamurai

Bindings for neutron. Slinky-related
Oracle:

- GetPrice
- GetAllCurrencyPairs

Marketmap:

- Params
- MarketMap
- LastUpdated

Main PR:
https://github.com/neutron-org/neutron/pull/508

2024-05-16 08:41 UTC, NeverHappened requested changes

2024-05-16 08:41 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/oracle/types.rs
> +    // block_timestamp: time.Time,
can you serialize it? or maybe write to skip to ask for better type?

2024-05-16 08:41 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/marketmap/query.rs
> +    // LastUpdated is the last block height that the market map was updated.
can we do all field comments in the typical rust docs manner?
like `/// **owner_address** is an address of contract which registered interchain account`

2024-05-16 08:41 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/marketmap/query.rs
> +pub enum MarketmapQuery {
`MarketMapQuery`?)

2024-05-16 15:47 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/oracle/types.rs
> +    // // BlockTimestamp tracks the block height associated with this price update.
double comment here

2024-05-17 14:36 UTC, NeverHappened commented on packages/neutron-sdk/src/bindings/marketmap/types.rs
> +    /// **Tickers** is the full list of tickers and their associated configurations
**ticker** ?

2024-05-17 14:39 UTC, NeverHappened approved these changes

2024-05-21 16:53 UTC, swelf19 commented on packages/neutron-sdk/src/bindings/marketmap/types.rs
> +    pub version: u64,
m, i actually do not see `vesrion` field in params type https://github.com/skip-mev/slinky/blob/main/x/marketmap/types/params.pb.go#L26 and do see `admin` field. Do i miss something?

2024-05-21 16:53 UTC, swelf19 commented on packages/neutron-sdk/src/bindings/oracle/query.rs
> +    pub id: Option<u64>,
i think `serde(default)` is a good choice here, to avoid unnecessary `id.unwrap()`, in this particular case `0 == None`

2024-05-21 16:53 UTC, swelf19 commented on packages/neutron-sdk/src/bindings/oracle/types.rs
> +pub struct CurrencyPair {
The same type defined in `marketmap` module. Does it make sence to extract it in a common package?

2024-05-22 12:40 UTC, quasisamurai commented
https://github.com/neutron-org/neutron-tests/actions/runs/9104146345

2024-05-22 14:30 UTC, swelf19 approved these changes

2024-05-22 14:32 UTC, merged