chore: add fees comment
neutron-org/neutron-sdk pull request #65
Opened 2022-11-28 15:28 UTC by NeverHappened

2022-12-14 08:48 UTC, foxpy requested changes
Target branch should be changed to `main`.

2022-12-14 09:48 UTC, pr0n00gler commented on packages/neutron-sdk/src/bindings/msg.rs
> +        // Fees that will be used for different callbacks.
Actually this comment doesn't clarify things (how exactly the fees are used for different callbacks).
Please, add a bit more info (and maybe a link to a relevant page in our documentation)

2023-02-25 18:34 UTC, foxpy approved these changes

2023-02-26 15:21 UTC, pr0n00gler approved these changes

2023-02-28 13:20 UTC, merged