chore: `InterchainQueries` → `NeutronQuery`
neutron-org/neutron-sdk pull request #75
Opened 2022-12-28 11:36 UTC by foxpy

2023-01-07 03:15 UTC, pr0n00gler submitted a review, later dismissed

2023-04-25 22:24 UTC, quasisamurai approved these changes

2023-04-26 05:08 UTC, sotnikov-s approved these changes

2023-04-26 09:03 UTC, oopcode requested changes
please update the docs

2023-04-28 09:39 UTC, oopcode approved these changes

2023-04-28 09:39 UTC, merged